
pipeline {

  agent {
    docker { 
      image 'python:2.7-alpine'
      args '--user root'
    }
    // docker { image 'python:3.5-alpine' }
    // docker { image 'python:2.7.16-slim' }
  }

  stages {
    stage('Pip Install') {
      when {
        changeset "**/vote/**"
      }
      steps {
        echo 'Installing Deps...'
        sh 'cd vote && pip install -r requirements.txt'
      }
    }

    stage('Test') {
      when {
        changeset "**/vote/**"
      }
      steps {
        echo 'Testing...'
        dir('vote') {
          sh 'pip install -r requirements.txt'
          sh 'nosetests -v'
        }
      }
    }
  }

  post {
    always {
      echo 'Pipeline for python worker is complete....'
    }
  }

}

