
pipeline {
  agent {
    docker {
      image "maven:3.6.1-jdk-8-alpine"
      // Setup a volume to cache maven artifacts for subsequent builds
      args '-v $HOME/.m2:/root/.m2'
    }
  }

  // triggers { pollSCM('H/2 * * * *') }

  /*
  No longer using the tools section...
  
  tools {
    maven 'Maven 3.6.3'
  }
  */

  stages {
    stage('Build') {
      when {
        changeset "**/worker/**"
      }
      steps {
        echo 'Building...'
        sh 'mvn -f worker/pom.xml compile'
      }
    }

    stage('Test') {
      when {
        changeset "**/worker/**"
      }
      steps {
        echo 'Testing...'
        sh 'mvn -f worker/pom.xml clean test'
      }
    }

    stage('Package') {
      when {
        branch 'master'
        changeset "**/worker/**"
      }
      steps {
        echo 'Packaging...'
        sh 'mvn -f worker/pom.xml package -DskipTests'
        archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
      }
    }
  }

  post {
    always {
      echo 'Pipeline for worker is complete...'
    }
    /*
      Optional Slack Notifications if you have slack integrated...

      failure{
      slackSend (channel: "instavote-cd", message: "Build Failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
    }

    success{
      slackSend (channel: "instavote-cd", message: "Build Succeeded - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
    }
     */
  }

}

