
pipeline {
  agent any

  // triggers { pollSCM('H/2 * * * *') }

  tools {
    maven 'Maven 3.6.3'
  }

  stages {
    stage('Build') {
      when {
        changeset "**/worker/**"
      }
      steps {
        echo 'Building...'
        sh 'mvn -f worker/pom.xml compile'
      }
    }

    stage('Test') {
      when {
        changeset "**/worker/**"
      }
      steps {
        echo 'Testing...'
        sh 'mvn -f worker/pom.xml clean test'
      }
    }

    stage('Package') {
      when {
        branch 'master'
        changeset "**/worker/**"
      }
      steps {
        echo 'Packaging...'
        sh 'mvn -f worker/pom.xml package -DskipTests'
        archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
      }
    }
  }

  post {
    always {
      echo 'Pipeline for worker is complete...'
    }
  }

}

